spring:
  application:
    name: OnlineOrders
  kafka:
    bootstrap-servers: localhost:9092
    partitions: 3

  datasource:
    url: jdbc:h2:mem:shop
    driver-class-name: org.h2.Driver
    username: shop
    password: shop

  h2:
    console:
      enabled: true